var domReady=function(){function i(a){for(e=1;a=g.shift();)a()}var g=[],c,a=document,h=a.documentElement,f=h.doScroll,e=/^loade|c/.test(a.readyState),d;a.addEventListener&&a.addEventListener("DOMContentLoaded",c=function(){a.removeEventListener("DOMContentLoaded",c,!1);i()},!1);f&&a.attachEvent("onreadystatechange",c=function(){/^c/.test(a.readyState)&&(a.detachEvent("onreadystatechange",c),i())});return d=f?function(a){if(self!=top)e?a():g.push(a);else a:{try{h.doScroll("left")}catch(c){setTimeout(function(){d(a)},
50);break a}a()}}:function(a){e?a():g.push(a)}}();
(function(){function i(a,b){var b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),c=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return null==c?"":c[1]}window.Tender=window.Tender||{};var g=!1,c,a,h=document.createElement("a");a=function(a){h.href=a;return{protocol:h.protocol,host:h.host}};for(var f=document.getElementsByTagName("script"),e=0;e<f.length;e++){var d=f[e].src;if(d.match(/tender_widget\.js(\?.*)?$/))var d=a(d),k=d.protocol+"//"+d.host+"/"}c=k;a={};f=document.getElementsByTagName("script");for(e=
0;e<f.length;e++)d=f[e].src,d.match(/tender_widget\.js(\?.*)?$/)&&(a.location=i(d,"location"),a.category=i(d,"category_id"));if(!c||""==c)c="//help.tenderapp.com/";var j=function(){if(!g){var a=document.createElement("div"),b=c+"widget/discussion/new?r="+Math.random();if("kb"==Tender.home||Tender.hide_discussion)b=c+"widget/faqs?";Tender.sso&&(b+="&sso="+encodeURIComponent(Tender.sso));Tender.widgetEmail&&(b+="&email="+encodeURIComponent(Tender.widgetEmail));!0===Tender.forcePrivate&&(b+="&private=1");
Tender.hide_kb&&(b+="&hide_kb=1");Tender.hide_discussion&&(b+="&hide_discussion=1");Tender.category&&(b+="&category="+encodeURIComponent(Tender.category));Tender.title&&(b+="&title="+encodeURIComponent(Tender.title));Tender.body&&(b+="&body="+encodeURIComponent(Tender.body));b+="&referrer="+escape(document.location);a.innerHTML='<div id="tender_window"><a href="#" id="tender_closer">Close</a><div id="tender_frame"><iframe src="'+b+'" scrolling="no" frameborder="0" width="100%" height="100%"></iframe></div></div>';
a.getElementsByTagName("iframe");document.body.appendChild(a);document.getElementById("tender_closer").onclick=function(){document.getElementById("tender_window").style.display="none";Tender.hideToggle||(document.getElementById("tender_toggler").style.display="");return!1};Tender.observer=function(a){a=a||window.event;if(27==(a.charCode||a.keyCode)||"TenderCloseWidget"==a.data)document.getElementById("tender_closer").onclick()};document.addEventListener?(document.body.addEventListener("keyup",Tender.observer,
!1),document.addEventListener("message",Tender.observer,!1)):document.attachEvent&&(document.body.attachEvent("onkeyup",Tender.observer),document.attachEvent("message",Tender.observer,!1));g=!0}document.getElementById("tender_window").style.display="";document.getElementById("tender_toggler").style.display="none"};Tender.showWidget=j;styles="#tender_window{ position: absolute; top: 20px; left: 10px; right: 10px; margin: auto; max-width:680px; height:715px; padding:3px; background:url("+c+"images/widget/overlay_back.png); z-index:9999; }";
styles+="#tender_window iframe{ border:none; width:100%; height:100%; } ";styles+="#tender_window #tender_frame{ width:100%; height:100%; background:url("+c+"images/widget/loader.gif) 50% 50% no-repeat #fff; } ";styles+="#tender_closer{ position:absolute; top:18px; right:18px; color:#fff; font-family:Helvetica, Arial, sans-serif; font-size:12px; font-weight:bold; text-decoration:none; border:none; } ";styles+="#tender_closer{ color: #80B3CC }";styles+="#tender_toggler{ position:absolute; top:100px; right:0px; width:33px; height:105px; padding:3px 0 3px 3px; background:url("+
c+"images/widget/overlay_back.png); } ";styles+="#tender_toggler_link{ display:block; width:100%; height:100%; text-decoration:none; border:none; text-indent:-9999px; background: #006699 url("+c+"images/widget/tab_text_"+(a.location||"right")+".gif) !important; } ";"left"==a.location?styles+="#tender_toggler{ top:100px; left:0px; width:33px; height:105px; padding:3px 3px 3px 0;  } ":"top"==a.location?styles+="#tender_toggler{ top:0; left:100px; width:105px; height:33px; padding:0 3px 3px 3px;":"bottom"==
a.location&&(styles+="#tender_toggler{ bottom:0; top:inherit; left:100px; width:105px; height:33px; padding:3px 3px 0 3px;");domReady(function(){var a=document.createElement("div");a.innerHTML='<div id="tender_toggler"><a href="#" id="tender_toggler_link">Help &amp; Support</a></div>';document.body.appendChild(a);document.getElementById("tender_toggler_link").onclick=function(){j();return!1};if(Tender.widgetToggles)for(a=0;a<Tender.widgetToggles.length;a++){var b=Tender.widgetToggles[a];null!=b&&
(b.onclick=function(){j();return!1})}Tender.hideToggle&&(document.getElementById("tender_toggler").style.display="none");a=document.createElement("style");a.setAttribute("type","text/css");a.setAttribute("charset","utf-8");try{a.appendChild(document.createTextNode(styles)),document.getElementsByTagName("head").item(0).appendChild(a)}catch(d){}document.createStyleSheet&&document.createStyleSheet(c+"tender_widget_styles.css")})})();
